Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "tooling"

  # Réseau privé (accès facile depuis ta machine)
  config.vm.network "private_network", ip: "192.168.56.30"

  # Ports utiles (si tu préfères accéder via localhost)
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true # Jenkins
  config.vm.network "forwarded_port", guest: 9000, host: 9000, auto_correct: true # SonarQube

  # Ressources (Sonar consomme)
  config.vm.provider "virtualbox" do |vb|
    vb.name = "tooling-vm"
    vb.memory = 8192
    vb.cpus = 2
  end

  # Provisioning via Ansible local (sur ta machine/WSL)
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/playbooks/bootstrap.yml"
    ansible.inventory_path = "provision/inventory.ini"
    ansible.limit = "tooling"
    ansible.extra_vars = {
      "ansible_python_interpreter" => "/usr/bin/python3"
    }
  end
end

