pipeline {
  agent any

  environment {
    AWS_REGION   = 'eu-west-3'
    AWS_ACCOUNT  = '418884735655'
    ECR_REPO     = 'hello-app'
    IMAGE_TAG    = "v0.1.${BUILD_NUMBER}"
    ECR_REGISTRY = "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE        = "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Tests') {
      steps {
        sh 'cd app/hello-app && ./test.sh'
      }
    }

    stage('SonarQube') {
      steps {
        withSonarQubeEnv('sonarqube') {
          sh '''
          sonar-scanner \
            -Dsonar.projectKey=hello-app \
            -Dsonar.sources=app/hello-app \
            -Dsonar.host.url=http://sonarqube:9000
          '''
        }
      }
    }

    stage('Build Image') {
      steps {
        sh '''
          cd app/hello-app
          docker build -t ${IMAGE} .
        '''
      }
    }

    stage('Trivy Scan Image') {
      steps {
        sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL ${IMAGE}'
      }
    }

    stage('Login & Push to ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          docker push ${IMAGE}
        '''
      }
    }

    stage('Update GitOps image tag') {
      steps {
        sh '''
          set -e
          git config user.email "jenkins@local"
          git config user.name "jenkins"

          # Exemple: si ton GitOps est dans le même repo, sinon on clone un repo dédié.
          sed -i "s#${AWS_ACCOUNT}\\.dkr\\.ecr\\.${AWS_REGION}\\.amazonaws\\.com/${ECR_REPO}:v0\\.1\\.[0-9]\\+#${IMAGE}#g" gitops/apps/hello/manifests.yaml || true
          sed -i "s#${AWS_ACCOUNT}\\.dkr\\.ecr\\.${AWS_REGION}\\.amazonaws\\.com/${ECR_REPO}:v0\\.1\\.[0-9]\\+#${IMAGE}#g" gitops/apps/hello/manifests.yaml

          git add gitops/apps/hello/manifests.yaml
          git commit -m "ci: bump hello-app image to ${IMAGE_TAG}" || true
          git push
        '''
      }
    }
  }
}

