pipeline {
  agent any
  options { timestamps() }

  environment {
    AWS_REGION   = 'eu-west-3'
    AWS_ACCOUNT  = '418884735655'
    ECR_REPO     = 'hello-app'
    IMAGE_TAG    = "v0.1.${BUILD_NUMBER}"
    ECR_REGISTRY = "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE        = "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Tests') {
      steps {
        sh 'cd app/hello-app && ./test.sh'
      }
    }

    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('sonarqube') {
          sh """
            sonar-scanner \
              -Dsonar.projectKey=hello-app \
              -Dsonar.sources=app/hello-app \
              -Dsonar.host.url=http://sonarqube:9000
          """
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

    stage('Build Image') {
      steps {
        sh """
          cd app/hello-app
          docker build -t ${IMAGE} .
        """
      }
    }

    stage('Trivy Scan Image') {
      steps {
        sh 'trivy image --no-progress --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed ${IMAGE}'
      }
    }

    stage('Login & Push to ECR') {
      steps {
        sh """
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          docker push ${IMAGE}
        """
      }
    }

    stage('Update GitOps image tag') {
      steps {
        sh """
          set -euo pipefail
          git config user.email "jenkins@local"
          git config user.name "jenkins"

          FILE="gitops/apps/hello/manifests.yaml"

          # Remplace la ligne image: .../hello-app:<tag> par la nouvelle image
          sed -i "s#^\\s*image: ${ECR_REGISTRY}/${ECR_REPO}:.*#        image: ${IMAGE}#g" \$FILE

          git add \$FILE
          git commit -m "ci: bump hello-app image to ${IMAGE_TAG}" || true
          git push origin HEAD:main
        """
      }
    }
  }
}

